import openColors from "open-color/open-color.json";

export enum Color {
  GRAY = "gray",
  RED = "red",
  PINK = "pink",
  GRAPE = "grape",
  VIOLET = "violet",
  INDIGO = "indigo",
  BLUE = "blue",
  CYAN = "cyan",
  TEAL = "teal",
  GREEN = "green",
  LIME = "lime",
  YELLOW = "yellow",
  ORANGE = "orange",
}

export const colors = {
  gray0: openColors.gray[0],
  gray1: openColors.gray[1],
  gray2: openColors.gray[2],
  gray3: openColors.gray[3],
  gray4: openColors.gray[4],
  gray5: openColors.gray[5],
  gray6: openColors.gray[6],
  gray7: openColors.gray[7],
  gray8: openColors.gray[8],
  gray9: openColors.gray[9],

  red0: openColors.red[0],
  red1: openColors.red[1],
  red2: openColors.red[2],
  red3: openColors.red[3],
  red4: openColors.red[4],
  red5: openColors.red[5],
  red6: openColors.red[6],
  red7: openColors.red[7],
  red8: openColors.red[8],
  red9: openColors.red[9],

  pink0: openColors.pink[0],
  pink1: openColors.pink[1],
  pink2: openColors.pink[2],
  pink3: openColors.pink[3],
  pink4: openColors.pink[4],
  pink5: openColors.pink[5],
  pink6: openColors.pink[6],
  pink7: openColors.pink[7],
  pink8: openColors.pink[8],
  pink9: openColors.pink[9],

  grape0: openColors.grape[0],
  grape1: openColors.grape[1],
  grape2: openColors.grape[2],
  grape3: openColors.grape[3],
  grape4: openColors.grape[4],
  grape5: openColors.grape[5],
  grape6: openColors.grape[6],
  grape7: openColors.grape[7],
  grape8: openColors.grape[8],
  grape9: openColors.grape[9],

  violet0: openColors.violet[0],
  violet1: openColors.violet[1],
  violet2: openColors.violet[2],
  violet3: openColors.violet[3],
  violet4: openColors.violet[4],
  violet5: openColors.violet[5],
  violet6: openColors.violet[6],
  violet7: openColors.violet[7],
  violet8: openColors.violet[8],
  violet9: openColors.violet[9],

  indigo0: openColors.indigo[0],
  indigo1: openColors.indigo[1],
  indigo2: openColors.indigo[2],
  indigo3: openColors.indigo[3],
  indigo4: openColors.indigo[4],
  indigo5: openColors.indigo[5],
  indigo6: openColors.indigo[6],
  indigo7: openColors.indigo[7],
  indigo8: openColors.indigo[8],
  indigo9: openColors.indigo[9],

  blue0: openColors.blue[0],
  blue1: openColors.blue[1],
  blue2: openColors.blue[2],
  blue3: openColors.blue[3],
  blue4: openColors.blue[4],
  blue5: openColors.blue[5],
  blue6: openColors.blue[6],
  blue7: openColors.blue[7],
  blue8: openColors.blue[8],
  blue9: openColors.blue[9],

  cyan0: openColors.cyan[0],
  cyan1: openColors.cyan[1],
  cyan2: openColors.cyan[2],
  cyan3: openColors.cyan[3],
  cyan4: openColors.cyan[4],
  cyan5: openColors.cyan[5],
  cyan6: openColors.cyan[6],
  cyan7: openColors.cyan[7],
  cyan8: openColors.cyan[8],
  cyan9: openColors.cyan[9],

  teal0: openColors.teal[0],
  teal1: openColors.teal[1],
  teal2: openColors.teal[2],
  teal3: openColors.teal[3],
  teal4: openColors.teal[4],
  teal5: openColors.teal[5],
  teal6: openColors.teal[6],
  teal7: openColors.teal[7],
  teal8: openColors.teal[8],
  teal9: openColors.teal[9],

  green0: openColors.green[0],
  green1: openColors.green[1],
  green2: openColors.green[2],
  green3: openColors.green[3],
  green4: openColors.green[4],
  green5: openColors.green[5],
  green6: openColors.green[6],
  green7: openColors.green[7],
  green8: openColors.green[8],
  green9: openColors.green[9],

  lime0: openColors.lime[0],
  lime1: openColors.lime[1],
  lime2: openColors.lime[2],
  lime3: openColors.lime[3],
  lime4: openColors.lime[4],
  lime5: openColors.lime[5],
  lime6: openColors.lime[6],
  lime7: openColors.lime[7],
  lime8: openColors.lime[8],
  lime9: openColors.lime[9],

  yellow0: openColors.yellow[0],
  yellow1: openColors.yellow[1],
  yellow2: openColors.yellow[2],
  yellow3: openColors.yellow[3],
  yellow4: openColors.yellow[4],
  yellow5: openColors.yellow[5],
  yellow6: openColors.yellow[6],
  yellow7: openColors.yellow[7],
  yellow8: openColors.yellow[8],
  yellow9: openColors.yellow[9],

  orange0: openColors.orange[0],
  orange1: openColors.orange[1],
  orange2: openColors.orange[2],
  orange3: openColors.orange[3],
  orange4: openColors.orange[4],
  orange5: openColors.orange[5],
  orange6: openColors.orange[6],
  orange7: openColors.orange[7],
  orange8: openColors.orange[8],
  orange9: openColors.orange[9],
};